### ISSUE TITLE
[django 1.9a1] cannot import name 'save_instance'

### ISSUE THREAD

**Issue by Kondou-ger** [gregmuellegger/django-floppyforms#161]
Floppyforms isn't compatible to django 1.9a1:

forms.py
```python
from captcha.fields import CaptchaField
import floppyforms.__future__ as forms
from floppyforms import widgets
from django.contrib.auth.forms import AuthenticationForm as AuthForm
...
```

```python-traceback
(project)kondou:project/ (master) $ ./manage.py shell
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/kondou/git/project/lib/python3.4/site-packages/django/core/management/__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "/home/kondou/git/project/lib/python3.4/site-packages/django/core/management/__init__.py", line 324, in execute
    django.setup()
  File "/home/kondou/git/project/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/kondou/git/project/lib/python3.4/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/kondou/git/project/lib/python3.4/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/home/kondou/git/project/lib64/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/kondou/git/project/lib/python3.4/site-packages/floppyforms/__init__.py", line 2, in <module>
    from django.forms import (BaseModelForm, model_to_dict, fields_for_model,
ImportError: cannot import name 'save_instance'
```

That's because `django.forms.save_instance` seems indeed gone:

```python
>>> from django.forms import save_instance
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'save_instance'
```

Is this a django regression? A quick Ctrl+F through the [release notes](https://docs.djangoproject.com/en/dev/releases/1.9/) doesn't say anything about `save_instance`, being removed …

If this seems to be I will report this at django.

### Edit:

Well apparently `save_instance` is an [internal function you're not supposed to use](https://github.com/django/django/commit/8656cfc4e01332426e5e4b78c20a4e9ec443b293) …

**Comment by gregmuellegger** [comment]
Hey, thanks for the report. This just got fixed with the merge of #160
